name: Project Automated Build

# 1. MIKOR fusson le?
# Minden egyes push eseményre elindul, ágtól függetlenül
on: push

# 2. MIT csináljon?
jobs:
  build-and-test:
    # Fontos: Ide az a címke (label) kell, amit a runnered támogat (az ubuntu-latest a szabvány)
    runs-on: ubuntu-latest

    steps:
      - name: Project Checkout
        uses: actions/checkout@v6

      # Go környezet beállítása (beépített verzió a Gitea/GitHub-tól)
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          # A go verziót a go.mod fájlból olvassa be
          go-version-file: 'go.mod'
          check-latest: true
          # Automatikusan gyorsítótárazza (cache-eli) a Go függőségeket, hogy villámgyors legyen a build
          cache: true

      # Telepíti a govulncheck-et, hogy a build során keresse meg a biztonsági hiányosságokat
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9

      - name: Run govulncheck
        run: govulncheck -test ./...

      # Itt hajtódik végre a te build parancsod
      - name: Project Build
        run: |
          make build