name: Project Automated Build

# 1. MIKOR fusson le?
# Minden egyes push eseményre elindul, ágtól függetlenül
on: push

# 2. MIT csináljon?
jobs:
  build-and-test:
    # Fontos: Ide az a címke (label) kell, amit a runnered támogat (az ubuntu-latest a szabvány)
    runs-on: ubuntu-latest

    steps:
      # Első lépés: A runner letölti a kódodat a saját virtuális környezetébe
      - name: Project Checkout
        uses: actions/checkout@v6

      # 2. Go környezet beállítása (beépített verzió a Gitea/GitHub-tól)
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          # Megadhatsz fix verziót is (pl. '1.22'), a 'stable' mindig a legfrissebbet rakja fel
          go-version: '1.25'
          # Automatikusan gyorsítótárazza (cache-eli) a Go függőségeket, hogy villámgyors legyen a build
          cache: true

      # Harmadik lépés: Itt hajtódik végre a te build parancsod
      - name: Project Build
        run: |
          make build